version: "3.8"
services:
  mox:
    image: eliavlavi/mox-server:0.5.2
    # operating mox on an irregular port allows testing support for these ports
    environment:
      - "PORT=8888"
    ports:
      - "8888:8888"

  httpbinmock:
    image: kennethreitz/httpbin:latest
    ports:
      - "8080:80"

  lunar-proxy:
    container_name: lunar-proxy
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      - "BIND_PORT=8000"
      - "TENANT_NAME=integration-tests"
      - "AWS_ACCESS_KEY_ID=LunarProxyAccessKeyID"
      - "AWS_SECRET_ACCESS_KEY=LunarProxySecretAccessKey"
      - LUNAR_REDIRECTION_BY_QUERY_PARAMS
      - LUNAR_SERVER_TIMEOUT_SEC=${LUNAR_SERVER_TIMEOUT_SEC:-15}
      - LUNAR_FLUSH_SECONDS=1 # used to ensure fast flushes so tests do not have to wait too much
      - DD_API_KEY=DataDogApiKey
      - LOG_LEVEL
    ports:
      - "2020:2020"
      - "3000:3000"
      - "8000:8000"
      - "8040:8040"
      - "8081:8081"
      - "10252:10252"
    depends_on:
      - mox
      - httpbinmock
      - minio

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=LunarProxyAccessKeyID"
      - "MINIO_ROOT_PASSWORD=LunarProxySecretAccessKey"
