name: Create Public Draft Release

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Release for service type"
        required: true
        type: string
      tag:
        description: "Release Tag"
        required: true
        type: string
      name:
        description: "Release Name"
        required: true
        type: string
      body:
          description: "Release Message"
          required: true
          type: string

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-22.04

    steps:
      - name: Create Public Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: $(echo "${{ inputs.body }}" | base64 -d)
          draft: true
          name: "${{ inputs.name }}"
          tag_name: "${{ inputs.tag }}"
          token: ${{ secrets.GITHUB_TOKEN }}